spring.application.name=payment-service
spring.datasource.url=jdbc:postgresql://localhost:5437/payment_service_db
spring.datasource.username=payment_service
spring.datasource.password=payment_password

server.port= 8084

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.cloud.openfeign.http2client.enabled=false
spring.cloud.openfeign.okhttp.enabled=true

order.service.url=http://localhost:8082


momo.partner-code=MOMO
momo.access-key=F8BBA842ECF85
momo.secret-key=K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.endpoint=https://test-payment.momo.vn/v2/gateway/api/create
momo.redirect-url=http://localhost:3000/payment-result
momo.ipn-url=http://localhost:8084/api/payments/momo/ipn
momo.request-type=captureWallet