server.port=8084
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/user_service_db?options=-c%20timezone=Asia/Ho_Chi_Minh
spring.datasource.username=user_service
spring.datasource.password=user_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
