spring.application.name=order-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5435/order_service_db?options=-c%20timezone=Asia/Ho_Chi_Minh
spring.datasource.username=order_service
spring.datasource.password=order_password

spring.cloud.openfeign.okhttp.enabled=true
spring.cloud.openfeign.httpclient.enabled=false


spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

product.service.url=http://localhost:8081
inventory.service.url=http://localhost:8083
