server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/user/**

            - id: product-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/product/**
              filters:
                - AuthenticationFilter
                
            - id: order-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/order/**
              filters:
                - AuthenticationFilter
                
            - id: inventory-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/inventory/**
              filters:
                - AuthenticationFilter
